In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
!unzip /content/drive/MyDrive/Colab_data/malware-detection-season5.zip

Archive:  /content/drive/MyDrive/Colab_data/malware-detection-season5.zip
  inflating: sample.csv
  inflating: test.csv
  inflating: train.csv

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample = pd.read_csv('sample.csv')

In [5]:
train.describe()

,id,label,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature2372,feature2373,feature2374,feature2375,feature2376,feature2377,feature2378,feature2379,feature2380,feature2381
count,107548.000000,107548.000000,107548.000000,1.075480e+05,1.075480e+05,107548.000000,107548.000000,107548.000000,107548.000000,107548.000000,...,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05,1.075480e+05
mean,53774.500000,0.426172,0.172821,1.009198e-02,6.502770e-03,0.005234,0.006889,0.004139,0.004872,0.003458,...,8.816818e+05,7.971457e+05,4.776766e+05,7.753348e+05,7.090279e+05,9.660098e+05,3.630547e+05,6.061281e+05,1.266013e+07,4.513464e+05
std,31046.577713,0.494522,0.190739,1.734650e-02,7.012532e-03,0.006103,0.008315,0.004257,0.005638,0.003957,...,4.830593e+07,3.651235e+07,3.692093e+07,4.644418e+07,5.478141e+07,4.103571e+07,2.962096e+07,3.628320e+07,1.493447e+08,3.479775e+07
min,1.000000,0.000000,0.000127,4.840046e-07,2.765741e-07,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,26887.750000,0.000000,0.018316,3.931403e-03,3.632774e-03,0.003146,0.003748,0.002588,0.002475,0.002126,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,53774.500000,0.000000,0.120941,6.528557e-03,4.367717e-03,0.003998,0.004729,0.003864,0.003807,0.003574,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.600000e+01,1.024000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,80661.250000,1.000000,0.250700,1.353488e-02,7.154557e-03,0.006337,0.008641,0.004910,0.005026,0.003977,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.920000e+02,1.310720e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,107548.000000,1.000000,0.999983,9.880831e-01,3.207031e-01,0.331557,0.362614,0.408537,0.314893,0.679162,...,3.286756e+09,3.590280e+09,3.758097e+09,3.347698e+09,4.283486e+09,3.914422e+09,3.771926e+09,3.823243e+09,3.758097e+09,2.906326e+09

In [6]:
train.head(10)

,id,label,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature2372,feature2373,feature2374,feature2375,feature2376,feature2377,feature2378,feature2379,feature2380,feature2381
0,1,1,0.004500,0.003912,0.003918,0.003906,0.003928,0.003897,0.003912,0.003918,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0,0.005672,0.003961,0.003897,0.003928,0.003918,0.003948,0.003895,0.003890,...,0.0,0.0,0.0,0.0,708.0,32768.0,0.0,0.0,0.0,0.0
2,3,0,0.170879,0.021148,0.024249,0.010553,0.029257,0.005464,0.015071,0.005795,...,0.0,0.0,0.0,0.0,8.0,8192.0,0.0,0.0,72.0,8200.0
3,4,0,0.007550,0.003954,0.003902,0.003914,0.003956,0.003897,0.003891,0.003864,...,0.0,0.0,0.0,0.0,652.0,28672.0,0.0,0.0,0.0,0.0
4,5,0,0.004280,0.003925,0.003915,0.003943,0.003914,0.003916,0.003947,0.003892,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,0,0.127215,0.005208,0.003416,0.003872,0.004498,0.004540,0.002883,0.003289,...,0.0,0.0,0.0,0.0,428.0,28672.0,0.0,0.0,0.0,0.0
6,7,0,0.201491,0.019507,0.014315,0.008410,0.015690,0.010754,0.010739,0.004228,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,62608.0
7,8,0,0.173054,0.019814,0.010605,0.010522,0.017457,0.012632,0.005755,0.005534,...,64.0,1203160.0,0.0,0.0,2164.0,847872.0,0.0,0.0,0.0,0.0
8,9,1,0.085016,0.004377,0.003478,0.004184,0.003336,0.003019,0.003495,0.003107,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,0,0.004613,0.003936,0.003911,0.003915,0.003979,0.003910,0.003912,0.003896,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

X = train.drop(columns = 'label')
y = train['label']

scaler = MinMaxScaler()
X_scaler = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaler, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import xgboost as xgb

rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)
rf_predict = rf.predict(X_test)

In [6]:
rf_acc = f1_score(y_test, rf_predict)

print(rf_acc)

0.9924188710117262

In [8]:
xgb_model = xgb.XGBClassifier(
    n_estimators=600,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=0.1,
    reg_lambda=1,
    n_jobs=-1,
    random_state=42,
    eval_metric="auc"
)

xgb_model.fit(X_scaler, y)

test_xcaler = scaler.transform(test)

xgb_predict = xgb_model.predict(test_xcaler)

In [10]:
submission = pd.DataFrame({
    'id' : test['id'],
    'label' : xgb_predict
})

submission.to_csv("submission.csv", index=False)