In [1]:
!pip -q install autogluon

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 kB 10.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 22.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.1/452.1 kB 39.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 38.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.8/244.8 kB 24.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.4/287.4 kB 29.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.0/281.0 kB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 82.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 48.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.9/827.9 kB 57.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.5/410.5 kB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 504.9/504.9 kB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.9/125.9 kB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.3/72.3 MB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 353.3/353.3 kB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 101.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 696.0 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 963.5/963.5 kB 63.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 98.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 102.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 82.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.9/131.9 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 96.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 kB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 38.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 56.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 42.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 100.2 MB/s eta 0:00:00
  Building wheel for nvidia-ml-py3 (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.10.0+cu128 requires torch==2.10.0, but you have torch 2.9.1 which is incompatible.
rasterio 1.5.0 requires click!=8.2.*,>=4.0, but you have click 8.2.1 which is incompatible.

In [2]:
import pandas as pd
from autogluon.tabular import TabularDataset, TabularPredictor

In [7]:
!unzip /content/super-ai-engineer-ss-6-heart-disease-prediction.zip

Archive:  /content/super-ai-engineer-ss-6-heart-disease-prediction.zip
  inflating: sample_submission.csv
  inflating: test.csv
  inflating: train.csv

In [8]:
train_data = pd.read_csv('/content/train.csv')
test_data = pd.read_csv('/content/test.csv')

In [9]:
train_data.columns

Index(['ID', 'History of HeartDisease or Attack', 'High Blood Pressure',
       'Told High Cholesterol', 'Cholesterol Checked', 'Body Mass Index',
       'Smoked 100+ Cigarettes', 'Diagnosed Stroke', 'Diagnosed Diabetes',
       'Leisure Physical Activity', 'Heavy Alcohol Consumption',
       'Health Care Coverage', 'Doctor Visit Cost Barrier', 'General Health',
       'Difficulty Walking', 'Sex', 'Education Level', 'Income Level', 'Age',
       'Vegetable or Fruit Intake (1+ per Day)'],
      dtype='object')

In [10]:
train_data['History of HeartDisease or Attack'].value_counts()

History of HeartDisease or Attack
No     203322
Yes     18068
Name: count, dtype: int64

In [11]:
print(len(train_data))
train_data = train_data.dropna(subset=['History of HeartDisease or Attack'])
print(len(train_data))

223084
221390

In [ ]:
def create_new_features(df):
    train_data = df.copy()

    binary_map = {"Yes": 1, "No": 0}
    binary_cols = [
        "High Blood Pressure", "Told High Cholesterol", "Cholesterol Checked",
        "Smoked 100+ Cigarettes", "Diagnosed Stroke", "Diagnosed Diabetes",
        "Leisure Physical Activity", "Heavy Alcohol Consumption",
        "Health Care Coverage", "Doctor Visit Cost Barrier",
        "Difficulty Walking", "Fruit or Vegetable Intake (1+ per Day)"
    ]

    # 2. แปลงค่าเป็นตัวเลข
    for col in binary_cols:
        if col in train_data.columns:
            if train_data[col].dtype == object:
                train_data[col] = train_data[col].map(binary_map)

    # 3. คำนวณ Obesity Risk
    if 'Body Mass Index' in train_data.columns and 'Leisure Physical Activity' in train_data.columns:
        train_data['Obesity Risk'] = ((train_data['Body Mass Index'] >= 30) & (train_data['Leisure Physical Activity'] == 0)).astype(int)

    # 4. จัดการ BMI Category
    def categorize_bmi(bmi):
        if bmi < 18.5: return 0 # Underweight
        if bmi < 25: return 1   # Normal
        if bmi < 30: return 2   # Overweight
        return 3                # Obese

    if 'Body Mass Index' in train_data.columns:
        train_data['BMI_Cat'] = train_data['Body Mass Index'].apply(categorize_bmi)

    return train_data

In [ ]:
def create_new_features_test(df):
    train_data = df.copy()

    binary_map = {"Yes": 1, "No": 0}
    binary_cols = [
        "High Blood Pressure", "Told High Cholesterol", "Cholesterol Checked",
        "Smoked 100+ Cigarettes", "Diagnosed Stroke", "Diagnosed Diabetes",
        "Leisure Physical Activity", "Heavy Alcohol Consumption",
        "Health Care Coverage", "Doctor Visit Cost Barrier",
        "Difficulty Walking", "Fruit or Vegetable Intake (1+ per Day)"
    ]

    # 2. แปลงค่าเป็นตัวเลข
    for col in binary_cols:
        if col in train_data.columns:
            if train_data[col].dtype == object:
                train_data[col] = train_data[col].map(binary_map)

    # 3. คำนวณ Obesity Risk
    if 'Body Mass Index' in train_data.columns and 'Leisure Physical Activity' in train_data.columns:
        train_data['Obesity Risk'] = ((train_data['Body Mass Index'] >= 30) & (train_data['Leisure Physical Activity'] == 0)).astype(int)

    # 4. จัดการ BMI Category
    def categorize_bmi(bmi):
        if bmi < 18.5: return 0
        if bmi < 25: return 1
        if bmi < 30: return 2
        return 3

    if 'Body Mass Index' in train_data.columns:
        train_data['BMI_Cat'] = train_data['Body Mass Index'].apply(categorize_bmi) # เปลี่ยนกลับเป็น BMI_Cat

    return train_data

In [14]:
train_data = create_new_features(train_data)
train_data.head(3)

,ID,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,...,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day),Obesity Risk,BMI_Cat
0,train_000001,No,1,1.0,1,40.68,1.0,0,0.0,0,...,0.0,Very Poor,1.0,Female,High school graduate,"$15,000 to less than $20,000",64,Yes,1,3
1,train_000002,No,0,0.0,0,24.36,1.0,0,0.0,1,...,1.0,Fair,0.0,Female,College graduate,"Less than $10,000",50,No,0,1
2,train_000003,No,1,1.0,1,27.33,0.0,0,0.0,0,...,1.0,Very Poor,1.0,Female,High school graduate,"$75,000 or more",61,Yes,0,2

In [15]:
df_yes = train_data[train_data['History of HeartDisease or Attack'] == 'Yes'].sample(n=18068, random_state=42)
df_no = train_data[train_data['History of HeartDisease or Attack'] == 'No'].sample(n=20000, random_state=42)

train_data = pd.concat([df_yes, df_no], ignore_index=True)

In [ ]:
save_path = 'best_model'
hyperparameters = {
    'GBM': [
        {'ag_args_fit': {'num_gpus': 0}},
        {'ag_args_fit': {'num_gpus': 1}}
    ],
    'CAT': [
        {'ag_args_fit': {'num_gpus': 0}},
        {'ag_args_fit': {'num_gpus': 1}}
    ],
    'XGB': [
        {'ag_args_fit': {'num_gpus': 0}},
        {'ag_args_fit': {'num_gpus': 1}}
    ],
    'RF': [
        {'ag_args_fit': {'num_gpus': 0}},
        {'ag_args_fit': {'num_gpus': 1}}
    ],

}
time_limit=3600

In [17]:
predictor = TabularPredictor(label='History of HeartDisease or Attack',
                            problem_type='binary',
                            path=save_path,
                            eval_metric='f1'
                            ).fit(
                                train_data,
                                presets='best_quality',
                                num_stack_levels=1,
                                num_bag_folds=5,
                                time_limit=time_limit,
                                hyperparameters=hyperparameters
                            )
print("Finish!")

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Mon Feb  2 12:27:57 UTC 2026
CPU Count:          2
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       10.97 GB / 12.67 GB (86.6%)
Disk Space Avail:   64.66 GB / 112.64 GB (57.4%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
DyStack: Disabling memory safe fit mode in DyStack because GPUs were detected and num_gpus='auto' (GPUs cannot be used in memory safe fit mode). If you want to use memory safe fit mode, manually set `num_gpus=0`.
Running DyStack sub-fit ...
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/content/best_model/ds_sub_fit/sub_fit_ho"
Train Data Rows:    33838
Train Data Columns: 21
Label Column:       History of HeartDisease or Attack
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Yes, class 0 = No
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11223.18 MB
	Train Data (Original)  Memory Usage: 15.63 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 11 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['ID']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['ID']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['Told High Cholesterol', 'Body Mass Index', 'Smoked 100+ Cigarettes', 'Diagnosed Diabetes', 'Doctor Visit Cost Barrier', ...]
		('int', [])    : 9 | ['High Blood Pressure', 'Cholesterol Checked', 'Diagnosed Stroke', 'Leisure Physical Activity', 'Heavy Alcohol Consumption', ...]
		('object', []) : 5 | ['General Health', 'Sex', 'Education Level', 'Income Level', 'Vegetable or Fruit Intake (1+ per Day)']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['General Health', 'Education Level', 'Income Level']
		('float', [])     :  4 | ['Told High Cholesterol', 'Body Mass Index', 'Diagnosed Diabetes', 'Difficulty Walking']
		('int', [])       :  2 | ['Age', 'BMI_Cat']
		('int', ['bool']) : 11 | ['High Blood Pressure', 'Cholesterol Checked', 'Smoked 100+ Cigarettes', 'Diagnosed Stroke', 'Leisure Physical Activity', ...]
	0.3s = Fit runtime
	20 features in original data used to generate 20 features in processed data.
	Train Data (Processed) Memory Usage: 2.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.4s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1'
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
	'CAT': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
	'XGB': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
	'RF': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 599.58s of the 899.59s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.30%)
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	0.7844	 = Validation score   (f1)
	27.75s	 = Training   runtime
	0.47s	 = Validation runtime
Fitting model: LightGBM_2_BAG_L1 ... Training model for up to 555.56s of the 855.57s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1.0 workers, per: cpus=1, gpus=1, memory=0.34%)
	0.7844	 = Validation score   (f1)
	37.12s	 = Training   runtime
	0.33s	 = Validation runtime
Fitting model: RandomForest_BAG_L1 ... Training model for up to 515.31s of the 815.33s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.2/9.5 GB
	0.7665	 = Validation score   (f1)
	13.74s	 = Training   runtime
	1.53s	 = Validation runtime
Fitting model: RandomForest_2_BAG_L1 ... Training model for up to 498.81s of the 798.82s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.2/9.8 GB
	0.7665	 = Validation score   (f1)
	12.96s	 = Training   runtime
	1.54s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 483.38s of the 783.40s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.18%)
	0.7824	 = Validation score   (f1)
	69.98s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_2_BAG_L1 ... Training model for up to 408.72s of the 708.74s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1.0 workers, per: cpus=1, gpus=1, memory=4.29%)
	0.7829	 = Validation score   (f1)
	105.95s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 299.65s of the 599.67s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.34%)
	0.7834	 = Validation score   (f1)
	21.2s	 = Training   runtime
	0.36s	 = Validation runtime
Fitting model: XGBoost_2_BAG_L1 ... Training model for up to 274.09s of the 574.11s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1.0 workers, per: cpus=1, gpus=1, memory=0.34%)
	0.7832	 = Validation score   (f1)
	18.69s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 552.53s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.3 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	0.7844	 = Validation score   (f1)
	2.09s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting 8 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2 ... Training model for up to 550.40s of the 550.39s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.42%)
	0.783	 = Validation score   (f1)
	23.27s	 = Training   runtime
	0.4s	 = Validation runtime
Fitting model: LightGBM_2_BAG_L2 ... Training model for up to 520.90s of the 520.89s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1.0 workers, per: cpus=1, gpus=1, memory=0.43%)
	0.783	 = Validation score   (f1)
	31.65s	 = Training   runtime
	0.21s	 = Validation runtime
Fitting model: RandomForest_BAG_L2 ... Training model for up to 484.65s of the 484.64s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.2/9.3 GB
	0.7782	 = Validation score   (f1)
	33.07s	 = Training   runtime
	1.58s	 = Validation runtime
Fitting model: RandomForest_2_BAG_L2 ... Training model for up to 449.47s of the 449.45s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.2/9.5 GB
	0.7782	 = Validation score   (f1)
	32.76s	 = Training   runtime
	2.07s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 413.83s of the 413.81s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.46%)
	0.7843	 = Validation score   (f1)
	52.57s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost_2_BAG_L2 ... Training model for up to 356.67s of the 356.66s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1.0 workers, per: cpus=1, gpus=1, memory=4.58%)
	0.7837	 = Validation score   (f1)
	72.38s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost_BAG_L2 ... Training model for up to 280.33s of the 280.32s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.48%)
	0.7849	 = Validation score   (f1)
	22.13s	 = Training   runtime
	0.23s	 = Validation runtime
Fitting model: XGBoost_2_BAG_L2 ... Training model for up to 253.71s of the 253.69s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1.0 workers, per: cpus=1, gpus=1, memory=0.47%)
	0.7849	 = Validation score   (f1)
	17.98s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 232.97s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
	Ensemble Weights: {'XGBoost_2_BAG_L2': 1.0}
	0.7849	 = Validation score   (f1)
	3.36s	 = Training   runtime
	0.01s	 = Validation runtime
AutoGluon training complete, total runtime = 670.45s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 3049.3 rows/s (6768 batch size)
Enabling decision threshold calibration (calibrate_decision_threshold='auto', metric is valid, problem_type is 'binary')
Calibrating decision threshold to optimize metric f1 | Checking 51 thresholds...
Calibrating decision threshold via fine-grained search | Checking 38 thresholds...
	Base Threshold: 0.500	| val: 0.7849
	Best Threshold: 0.397	| val: 0.7908
Updating predictor.decision_threshold from 0.5 -> 0.397
	This will impact how prediction probabilities are converted to predictions in binary classification.
	Prediction probabilities of the positive class >0.397 will be predicted as the positive class (Yes). This can significantly impact metric scores.
	You can update this value via `predictor.set_decision_threshold`.
	You can calculate an optimal decision threshold on the validation data via `predictor.calibrate_decision_threshold()`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/best_model/ds_sub_fit/sub_fit_ho")
Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                    model  score_holdout  score_val eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0       CatBoost_2_BAG_L1       0.781955   0.782938          f1        0.053807       0.131692  105.949518                 0.053807                0.131692         105.949518            1       True          6
1       LightGBM_2_BAG_L2       0.781466   0.783029          f1        5.325450       4.757133  339.041790                 0.128675                0.207602          31.647589            2       True         11
2       CatBoost_2_BAG_L2       0.781404   0.783657          f1        5.233202       4.634500  379.773252                 0.036427                0.084968          72.379051            2       True         15
3         CatBoost_BAG_L2       0.780978   0.784348          f1        5.229214       4.631490  359.963458                 0.032439                0.081959          52.569257            2       True         14
4        XGBoost_2_BAG_L1       0.780682   0.783198          f1        0.127247       0.106011   18.694144                 0.127247                0.106011          18.694144            1       True          8
5          XGBoost_BAG_L1       0.780585   0.783375          f1        0.577471       0.357889   21.202903                 0.577471                0.357889          21.202903            1       True          7
6         LightGBM_BAG_L2       0.780553   0.783024          f1        5.316864       4.953552  330.666352                 0.120090                0.404021          23.272151            2       True         10
7         CatBoost_BAG_L1       0.780315   0.782381          f1        0.205786       0.090597   69.980175                 0.205786                0.090597          69.980175            1       True          5
8        XGBoost_2_BAG_L2       0.780053   0.784896          f1        5.323325       4.669679  325.373232                 0.126550                0.120148          17.979031            2       True         17
9     WeightedEnsemble_L3       0.780053   0.784896          f1        5.324916       4.681935  328.736867                 0.001590                0.012256           3.363636            3       True         18
10         XGBoost_BAG_L2       0.779510   0.784863          f1        5.299821       4.780836  329.522765                 0.103046                0.231305          22.128564            2       True         16
11      LightGBM_2_BAG_L1       0.777581   0.784435          f1        0.213111       0.329609   37.117756                 0.213111                0.329609          37.117756            1       True          2
12        LightGBM_BAG_L1       0.777581   0.784435          f1        2.220546       0.467933   27.747804                 2.220546                0.467933          27.747804            1       True          1
13    WeightedEnsemble_L2       0.777581   0.784435          f1        2.221986       0.483206   29.839434                 0.001440                0.015273           2.091630            2       True          9
14    RandomForest_BAG_L2       0.774538   0.778160          f1        5.827287       6.128137  340.460034                 0.630512                1.578606          33.065833            2       True         12
15  RandomForest_2_BAG_L2       0.774538   0.778160          f1        5.894160       6.617629  340.151190                 0.697386                2.068098          32.756989            2       True         13
16  RandomForest_2_BAG_L1       0.767209   0.766528          f1        0.867220       1.540639   12.958516                 0.867220                1.540639          12.958516            1       True          4
17    RandomForest_BAG_L1       0.767209   0.766528          f1        0.931587       1.525160   13.743385                 0.931587                1.525160          13.743385            1       True          3
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	680s	 = DyStack   runtime |	2920s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 2920s
AutoGluon will save models to "/content/best_model"
Train Data Rows:    38068
Train Data Columns: 21
Label Column:       History of HeartDisease or Attack
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Yes, class 0 = No
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9644.99 MB
	Train Data (Original)  Memory Usage: 17.62 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 11 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['ID']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['ID']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['Told High Cholesterol', 'Body Mass Index', 'Smoked 100+ Cigarettes', 'Diagnosed Diabetes', 'Doctor Visit Cost Barrier', ...]
		('int', [])    : 9 | ['High Blood Pressure', 'Cholesterol Checked', 'Diagnosed Stroke', 'Leisure Physical Activity', 'Heavy Alcohol Consumption', ...]
		('object', []) : 5 | ['General Health', 'Sex', 'Education Level', 'Income Level', 'Vegetable or Fruit Intake (1+ per Day)']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['General Health', 'Education Level', 'Income Level']
		('float', [])     :  4 | ['Told High Cholesterol', 'Body Mass Index', 'Diagnosed Diabetes', 'Difficulty Walking']
		('int', [])       :  2 | ['Age', 'BMI_Cat']
		('int', ['bool']) : 11 | ['High Blood Pressure', 'Cholesterol Checked', 'Smoked 100+ Cigarettes', 'Diagnosed Stroke', 'Leisure Physical Activity', ...]
	0.4s = Fit runtime
	20 features in original data used to generate 20 features in processed data.
	Train Data (Processed) Memory Usage: 2.25 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.42s ...

Finish!

In [23]:
test_data = create_new_features_test(test_data)

In [24]:
y_pred = predictor.predict_proba(test_data)
y_pred.head()

         No       Yes
0  0.517972  0.482028
1  0.679688  0.320312
2  0.318191  0.681809
3  0.836099  0.163901
4  0.849792  0.150208

In [25]:
y_pred['outcome'] = y_pred.apply(lambda row: 'Yes' if row['Yes'] > 0.505 else 'No', axis=1)
y_pred['outcome'].value_counts()

outcome
No     49947
Yes    24414
Name: count, dtype: int64

In [26]:
sample_submission = pd.read_csv("/content/sample_submission.csv")
sample_submission.head(2)

            ID History of HeartDisease or Attack
0  test_000001                                No
1  test_000002                                No

In [27]:
sample_submission['History of HeartDisease or Attack'] = y_pred['outcome']
sample_submission.tail()

                ID History of HeartDisease or Attack
74356  test_074357                                No
74357  test_074358                               Yes
74358  test_074359                               Yes
74359  test_074360                               Yes
74360  test_074361                                No

In [28]:
sample_submission.to_csv("submission_heart_disease_prediction.csv", index=False)

In [29]:
from google.colab import files

files.download('submission_heart_disease_prediction.csv')